[project]
name = "cot-faith"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.49.0",
    "datasets>=3.5.0",
    "filelock>=3.18.0",
    "openai>=1.74.0",
]
